/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tester_3 (
    input i,
    input clk,
    input rst,
    output reg [7:0] a,
    output reg [7:0] b,
    output reg [4:0] alufn,
    output reg [3:0] testcase
  );
  
  
  
  reg [5:0] M_accum_d, M_accum_q = 1'h0;
  
  always @* begin
    M_accum_d = M_accum_q;
    
    M_accum_d = M_accum_q + i;
    testcase = M_accum_q[2+3-:4];
    
    case (M_accum_q[2+3-:4])
      1'h0: begin
        a = $signed(5'h12);
        b = 4'hf;
        alufn = 5'h00;
      end
      1'h1: begin
        a = 8'h7f;
        b = 8'h01;
        alufn = 5'h00;
      end
      2'h2: begin
        a = 8'h80;
        b = 8'hff;
        alufn = 6'h01;
      end
      2'h3: begin
        a = 8'h81;
        b = 8'h02;
        alufn = 6'h23;
      end
      3'h4: begin
        a = 8'h04;
        b = 8'h04;
        alufn = 6'h02;
      end
      3'h5: begin
        a = $signed(2'h3);
        b = 1'h1;
        alufn = 6'h35;
      end
      3'h6: begin
        a = 8'h0c;
        b = 8'h0a;
        alufn = 6'h18;
      end
      default: begin
        a = 8'h00;
        b = 8'h00;
        alufn = 5'h00;
        M_accum_d = 1'h0;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_accum_q <= 1'h0;
    end else begin
      M_accum_q <= M_accum_d;
    end
  end
  
endmodule
